# Generated by Django 4.2.1 on 2023-05-08 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_alter_onboardingdata_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingdata',
            name='survey_id',
            field=models.UUIDField(default=uuid.UUID('33ac0593-b44d-4696-82f0-fd1a2bd53bf9'), editable=False, unique=True),
        ),
    ]
