# Generated by Django 4.2.1 on 2023-05-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_alter_onboardingdata_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingdata',
            name='crypto_network',
            field=models.CharField(choices=[('MATIC', 'Polygon'), ('ETH', 'Ethereum')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingdata',
            name='gift_card_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingdata',
            name='gift_card_amount_currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingdata',
            name='gift_card_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingdata',
            name='gift_card_price_currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingdata',
            name='store_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
